import {useEffect,useState} from 'react'
import {Link,Navigate,useLocation,useNavigate} from 'react-router-dom'
import {ArrowLeft,GraduationCap,Mail,ShieldCheck} from 'lucide-react'
import {Brand,Field,ErrorBox,Submit,useFormAction,str,Loading} from './ui'
import {auth} from '../services/auth'
import {useStore} from '../lib/store'
export function AuthPage({mode}:{mode:'login'|'signup'|'reset'|'recovery'}){
const {session,ready}=useStore(),navigate=useNavigate(),location=useLocation();const [backendReady,setBackendReady]=useState<boolean|null>(null);useEffect(()=>{let alive=true;void auth.health().then(status=>{if(alive)setBackendReady(status.configured&&status.databaseReady)}).catch(()=>{if(alive)setBackendReady(false)});return()=>{alive=false}},[]);const [message,setMessage]=useState('');const [callbackError]=useState(()=>{const e=sessionStorage.getItem('auth_error')||new URLSearchParams(location.search).get('auth_error')||'';sessionStorage.removeItem('auth_error');return e});const {run,busy,error}=useFormAction()
if(session&&mode==='login')return <Navigate to="/app" replace/>
const heading={login:'Kaldığın yerden devam.',signup:'Kampüsüne hoş geldin.',reset:'Şifreni yenileyelim.',recovery:'Yeni bir başlangıç.'}[mode]
return <div className="auth-page"><div className="auth-aside"><Brand/><div><span className="eyebrow">HER GÜN BİRAZ DAHA KOLAY</span><h1>Bir kampüs.<br/>Bin ihtimal.<br/><span>Senin kitin.</span></h1><p>Dersinden ilk stajına, yeni evinden<br/>yeni arkadaşlarına kadar yanındayız.</p></div><img src="/campus.png" alt="Güneşli bir kampüs avlusu"/></div><main className="auth-main"><Link className="back-link" to="/"><ArrowLeft size={16}/> Ana sayfaya dön</Link><div className="auth-card"><span className="icon-tile blue"><GraduationCap size={27}/></span><h1>{heading}</h1><p>{mode==='signup'?'Bir hesapla kampüs hayatının bütün parçaları.':mode==='reset'?'E-posta adresine şifre yenileme bağlantısı göndereceğiz.':'Kampüs hayatına kaldığın yerden katıl.'}</p>
{backendReady===false&&<div className="setup-notice"><ShieldCheck size={22}/><div><strong>Hesap bağlantısı hazırlanıyor.</strong><p>Gerçek kayıt ve giriş, veritabanı kurulumu tamamlandığında açılacak. Bu sırada örnek içerikleri keşfedebilirsin.</p><Link to="/demo">Örnek kampüsü keşfet →</Link></div></div>}
{message?<div className="success-message" role="status"><Mail size={32}/><h3>E-postanı kontrol et.</h3><p>{message}</p><Link className="button secondary" to="/giris">Giriş ekranına dön</Link></div>:<form onSubmit={e=>run(e,async f=>{const email=str(f,'email'),password=String(f.get('password')||'');if(mode==='signup'){const result=await auth.signup(email,password);if(result.session){navigate('/app');return}setMessage('Hesabını doğrulamak için gelen bağlantıya dokun. Ardından üniversiteni seçebilirsin.')}else if(mode==='login'){await auth.login(email,password);navigate('/app')}else if(mode==='reset'){await auth.reset(email);setMessage('Bu adresle bir hesap varsa şifre yenileme bağlantısı gönderildi.')}else{if(password!==String(f.get('confirm')||''))throw new Error('Şifreler aynı olmalı.');await auth.updatePassword(password);navigate('/app')}})}>
{mode!=='recovery'&&<Field label="E-posta adresi"><input name="email" type="email" autoComplete="email" placeholder="sen@universite.edu.tr" required maxLength={254}/></Field>}
{mode!=='reset'&&<Field label={mode==='recovery'?'Yeni şifre':'Şifre'}><input name="password" type="password" minLength={8} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} placeholder="En az 8 karakter" required/></Field>}
{mode==='recovery'&&<Field label="Şifreni tekrar yaz"><input name="confirm" type="password" minLength={8} autoComplete="new-password" required/></Field>}
{mode==='login'&&<Link className="forgot-link" to="/sifremi-unuttum">Şifremi unuttum</Link>}
<ErrorBox message={error||callbackError}/><Submit busy={busy||!ready||backendReady!==true} label={{login:'Giriş yap',signup:'Hesabımı oluştur',reset:'Yenileme bağlantısı gönder',recovery:'Şifreyi güncelle'}[mode]}/>
</form>}
{mode==='login'?<p className="auth-switch">Henüz hesabın yok mu? <Link to="/kayit">Kampüsüne katıl</Link></p>:mode==='signup'?<p className="auth-switch">Zaten üye misin? <Link to="/giris">Giriş yap</Link></p>:null}<p className="auth-foot">Üniversite seçimi resmi öğrencilik doğrulaması değildir.</p></div></main></div>
}
export function Gate({children}:{children:React.ReactNode}){const {demo,ready,session,profile,loading,error}=useStore();if(demo)return children;if(!ready||loading)return <Loading/>;if(!session)return <Navigate to="/giris" replace/>;if(!profile&&!error)return <Onboarding/>;return children}
export function Onboarding(){const {data,saveProfile,error:loadError,refresh}=useStore(),{run,busy,error}=useFormAction();return <div className="onboarding"><Brand/><div className="auth-card"><span className="icon-tile yellow"><GraduationCap/></span><h1>Önce seni tanıyalım.</h1><p>Kampüsüne ait içerikleri senin için bir araya getirelim.</p><form onSubmit={e=>run(e,async f=>saveProfile({display_name:str(f,'display_name'),university_id:str(f,'university_id'),department:str(f,'department')}))}><Field label="Adın"><input name="display_name" required maxLength={60}/></Field><Field label="Üniversiten"><select name="university_id" required defaultValue=""><option value="" disabled>Üniversiteni seç</option>{data.universities.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Bölümün"><input name="department" required maxLength={100}/></Field><ErrorBox message={error||loadError}/>{loadError&&<button type="button" className="text-button" onClick={()=>void refresh()}>Yeniden yükle</button>}<Submit busy={busy} label="Kampüsüme git"/></form></div></div>}
export function ScrollTop(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo(0,0)},[pathname]);return null}
