import {useEffect,useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import {Plus,MessageCircle,FileText,ArrowUpRight,Trash2,Download} from 'lucide-react'
import {useStore,errorText} from '../lib/store'
import {PageHead,SearchBox,Badge,Example,Empty,Modal,Field,ErrorBox,Submit,useFormAction,str} from '../components/ui'
import {safeExternalUrl,trDate} from '@kampuskit/shared/domain'
import type {Post} from '@kampuskit/shared/types'
export function NotesPage(){const s=useStore(),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[course,setCourse]=useState(''),[open,setOpen]=useState(false),[selected,setSelected]=useState<Post|null>(null),[params,setParams]=useSearchParams();const courses=s.data.courses.filter(c=>c.university_id===s.universityId)
useEffect(()=>{if(params.get('yeni')){setOpen(true);setParams({}, {replace:true})}},[params,setParams])
useEffect(()=>{setCourse('');setSelected(null)},[s.universityId])
const posts=s.data.posts.filter(p=>p.university_id===s.universityId&&p.published&&(kind==='all'||p.kind===kind)&&(!course||p.course_id===course)&&(p.title+' '+p.body).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')))
return <><PageHead eyebrow="BİLGİ PAYLAŞTIKÇA ÇOĞALIR" title="Notlar & sorular" description="Birlikte çalış, takıldığını sor, bildiklerini paylaş."><button className="button" onClick={()=>setOpen(true)}><Plus size={18}/>Paylaşım yap</button></PageHead><div className="filter-bar"><div className="tabs">{[['all','Tümü'],['note','Ders notları'],['question','Sorular']].map(([v,t])=><button className={kind===v?'active':''} onClick={()=>setKind(v)} key={v}>{t}</button>)}</div><SearchBox value={query} onChange={setQuery} placeholder="Not veya soru ara"/><select aria-label="Derse göre filtrele" value={course} onChange={e=>setCourse(e.target.value)}><option value="">Bütün dersler</option>{courses.map(c=><option key={c.id} value={c.id}>{c.code}</option>)}</select></div>
<div className="content-grid">{posts.map(p=><button className="panel content-card note-card" key={p.id} onClick={()=>setSelected(p)}><div className="card-top"><span className={'icon-tile '+(p.kind==='note'?'blue':'yellow')}>{p.kind==='note'?<FileText size={23}/>:<MessageCircle size={23}/>}</span><Badge tone={p.kind==='note'?'blue':'yellow'}>{p.kind==='note'?'Ders notu':'Soru'}</Badge></div><span className="course-code">{courses.find(c=>c.id===p.course_id)?.code}</span><h2>{p.title}</h2><p className="clamp-3">{p.body}</p><div className="card-meta"><span>{s.data.members.find(m=>m.id===p.user_id)?.display_name||'Öğrenci'} · {trDate(p.created_at)}</span><ArrowUpRight size={17}/></div><Example value={p.is_example}/></button>)}</div>{!posts.length&&<Empty title="Bu aramada paylaşım bulunamadı." text="Başka bir ders seç veya ilk paylaşımı yap."/>}
{open&&<PostForm onClose={()=>setOpen(false)}/>} {selected&&<PostDetail post={s.data.posts.find(p=>p.id===selected.id)||selected} onClose={()=>setSelected(null)}/>}</>}
function PostForm({onClose}:{onClose:()=>void}){const s=useStore(),{run,busy,error}=useFormAction(onClose),[kind,setKind]=useState('note');const [uploaded,setUploaded]=useState<string|null>(null);return <Modal title="Kampüsle paylaş" onClose={onClose}><form onSubmit={e=>run(e,async f=>{const link=str(f,'link_url');if(link&&!safeExternalUrl(link))throw new Error('Geçerli bir http veya https bağlantısı gir.');let attachment=uploaded;const file=f.get('file') as File;if(file?.size){attachment=await s.upload(file,'notes');setUploaded(attachment)}await s.save('posts',{university_id:s.universityId,course_id:str(f,'course_id'),kind:kind as 'note'|'question',title:str(f,'title'),body:str(f,'body'),link_url:link||null,attachment_path:attachment,published:true})})}><div className="form-grid"><Field label="Paylaşım türü"><select name="kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="note">Ders notu</option><option value="question">Soru</option></select></Field><Field label="Ders"><select name="course_id" required>{s.data.courses.filter(c=>c.university_id===s.universityId).map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></Field><Field label="Başlık" wide><input name="title" required minLength={3} maxLength={150}/></Field><Field label={kind==='note'?'Notun veya açıklaman':'Sorun'} wide><textarea name="body" required rows={5} maxLength={10000}/></Field>{kind==='note'&&<><Field label="Kaynak bağlantısı (isteğe bağlı)" wide><input name="link_url" type="url" placeholder="https://…"/></Field><Field label="PDF ekle · en fazla 10 MB" wide><input name="file" type="file" accept="application/pdf"/>{uploaded&&<small>Dosyan yüklendi; paylaşım kaydedildiğinde görünür olacak.</small>}</Field></>}</div><ErrorBox message={error}/><div className="form-footer"><span>Seçili üniversitenin öğrencileriyle paylaşılır.</span><Submit busy={busy} label="Paylaş"/></div></form></Modal>}
function PostDetail({post,onClose}:{post:Post;onClose:()=>void}){const s=useStore(),{run,busy,error}=useFormAction();const replies=s.data.replies.filter(r=>r.post_id===post.id);return <Modal title={post.title} onClose={onClose} wide><div className="detail-body"><div className="detail-meta"><Badge>{post.kind==='note'?'Ders notu':'Soru'}</Badge><Example value={post.is_example}/><span>{trDate(post.created_at)}</span></div><p className="prose">{post.body}</p><div className="row-actions">{post.link_url&&safeExternalUrl(post.link_url)&&<a className="button secondary small" href={safeExternalUrl(post.link_url)!} target="_blank" rel="noopener noreferrer">Kaynağı aç <ArrowUpRight size={16}/></a>}{post.attachment_path&&<button className="button secondary small" onClick={()=>void s.download('notes',post.attachment_path!,post.title+'.pdf').catch(e=>s.notify(errorText(e)))}><Download size={16}/>PDF indir</button>}{post.user_id===s.userId&&!post.is_example&&<button className="danger-button" onClick={()=>void s.remove('posts',post.id).then(onClose).catch(e=>s.notify(errorText(e)))}><Trash2 size={16}/>Paylaşımı sil</button>}</div><h3 className="replies-heading">{replies.length} yanıt</h3>{replies.map(r=><div className="reply" key={r.id}><strong>{s.data.members.find(m=>m.id===r.user_id)?.display_name||'Öğrenci'}</strong><p>{r.body}</p></div>)}<form onSubmit={e=>{const form=e.currentTarget;void run(e,async f=>{await s.save('replies',{post_id:post.id,body:str(f,'body')});form.reset()})}}><Field label="Senin yanıtın"><textarea name="body" rows={3} required maxLength={5000} placeholder="Birlikte çözelim…"/></Field><ErrorBox message={error}/><Submit busy={busy} label="Yanıtla"/></form></div></Modal>}
