import {useEffect,useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import {Plus,ArrowDownLeft,ArrowUpRight,Wallet,Trash2,Utensils,House,Bus,BookOpen,Coffee} from 'lucide-react'
import {useStore,errorText} from '../lib/store'
import {PageHead,Empty,Modal,Field,ErrorBox,Submit,useFormAction,str} from '../components/ui'
import {money,toKurus,budgetSummary,monthKey,dateKey,trDate} from '@kampuskit/shared/domain'
const categories=['Yemek','Barınma','Ulaşım','Ders','Sosyal','Diğer']
const colors=['#3158e0','#8f9ef4','#f4c659','#62b4a0','#e59ba8','#b7c0d2']
export function BudgetPage(){const s=useStore(),[month,setMonth]=useState(monthKey()),[open,setOpen]=useState(false),[params,setParams]=useSearchParams(),summary=budgetSummary(s.data.budget_entries,month)
useEffect(()=>{if(params.get('yeni')){setOpen(true);setParams({}, {replace:true})}},[params,setParams])
const grouped=categories.map((c,i)=>({category:c,color:colors[i],value:summary.entries.filter(e=>e.type==='expense'&&e.category===c).reduce((a,e)=>a+e.amount_kurus,0)}));let offset=0;const gradient=grouped.filter(g=>g.value).map(g=>{const from=offset;offset+=g.value/(summary.expense||1)*100;return g.color+' '+from+'% '+offset+'%'}).join(',')
return <><PageHead eyebrow="AY SONUNA BİRAZ RAHATLIK" title="Bütçem" description="Küçük harcamaları gör, bütçene nefes aldır."><button className="button" onClick={()=>setOpen(true)}><Plus size={18}/>Gelir / gider ekle</button></PageHead><div className="filter-bar"><label className="month-picker">Gösterilen ay <input aria-label="Bütçe ayı" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div><div className="budget-stats">{[{label:'Toplam gelir',value:summary.income,icon:ArrowDownLeft,color:'green'},{label:'Toplam gider',value:summary.expense,icon:ArrowUpRight,color:'pink'},{label:'Kalan bütçe',value:summary.balance,icon:Wallet,color:'blue'}].map(x=><div className="panel budget-stat" key={x.label}><span className={'icon-tile '+x.color}><x.icon size={23}/></span><div><p>{x.label}</p><strong>{money(x.value)}</strong></div></div>)}</div>
<div className="budget-layout"><section className="panel"><div className="panel-heading"><h2>Harcama dağılımı</h2><span className="muted">Bu ay</span></div><div className="donut-wrap"><div className="donut" role="img" aria-label={'Toplam gider '+money(summary.expense)} style={{background:gradient?'conic-gradient('+gradient+')':'#eef1f7'}}><div><span>Toplam gider</span><strong>{money(summary.expense)}</strong></div></div></div><div className="budget-legend">{grouped.map(g=><div key={g.category}><span className="legend-swatch" style={{background:g.color}}/><span>{g.category}</span><strong>{money(g.value)}</strong></div>)}</div></section>
<section className="panel"><div className="panel-heading"><h2>Hareketler</h2><span className="muted">{summary.entries.length} kayıt</span></div>{[...summary.entries].sort((a,b)=>b.occurred_on.localeCompare(a.occurred_on)).map(e=>{const Icon=e.type==='income'?ArrowDownLeft:e.category==='Yemek'?Utensils:e.category==='Barınma'?House:e.category==='Ulaşım'?Bus:e.category==='Ders'?BookOpen:Coffee;return <div className="transaction" key={e.id}><span className={'icon-tile '+(e.type==='income'?'green':'blue')}><Icon size={19}/></span><div><strong>{e.note||e.category}</strong><span>{e.category} · {trDate(e.occurred_on)}</span></div><b className={e.type==='income'?'income-text':''}>{e.type==='income'?'+':'−'}{money(e.amount_kurus)}</b><button className="icon-button" aria-label={e.note+' kaydını sil'} onClick={()=>void s.remove('budget_entries',e.id).catch(e=>s.notify(errorText(e)))}><Trash2 size={16}/></button></div>})}{!summary.entries.length&&<Empty title="Bu ayın sayfası henüz boş." text="İlk gelir veya giderini ekle; hesabı birlikte tutalım."/>}</section></div>{open&&<BudgetForm onClose={()=>setOpen(false)}/>}</>}
function BudgetForm({onClose}:{onClose:()=>void}){const s=useStore(),{run,busy,error}=useFormAction(onClose),[type,setType]=useState('expense');return <Modal title="Bütçene bir kayıt ekle" onClose={onClose}><form onSubmit={e=>run(e,async f=>s.save('budget_entries',{type:type as 'income'|'expense',amount_kurus:toKurus(str(f,'amount')),category:str(f,'category'),note:str(f,'note'),occurred_on:str(f,'occurred_on')}))}><div className="form-grid"><Field label="İşlem"><select name="type" value={type} onChange={e=>setType(e.target.value)}><option value="expense">Gider</option><option value="income">Gelir</option></select></Field><Field label="Tutar (TL)"><input name="amount" required inputMode="decimal" placeholder="0,00"/></Field><Field label="Kategori"><select name="category">{(type==='expense'?categories:['Aylık destek','Burs','Maaş','Diğer']).map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Tarih"><input name="occurred_on" type="date" required defaultValue={dateKey()}/></Field><Field label="Kısa not (isteğe bağlı)" wide><input name="note" maxLength={200} placeholder="Örn. Yemekhane, aylık burs…"/></Field></div><ErrorBox message={error}/><div className="form-footer"><span>Bütçe kayıtlarını yalnızca sen görürsün.</span><Submit busy={busy}/></div></form></Modal>}
