import {Link} from 'react-router-dom'
import {ArrowUpRight,ArrowRight,BookOpen,Wallet,Users,CalendarDays,Plus,ShoppingBag,BriefcaseBusiness,Clock,Library,Utensils,Sun,CheckCircle2} from 'lucide-react'
import {useStore} from '../lib/store'
import {useAppPath} from '../components/layout'
import {budgetSummary,monthKey,money,trDate,crowdSummary} from '@kampuskit/shared/domain'
import {Badge,Example,Empty} from '../components/ui'
export default function Dashboard(){const {data,profile,universityId,demo}=useStore(),base=useAppPath();const uni=data.universities.find(u=>u.id===universityId),budget=budgetSummary(data.budget_entries,monthKey());const upcoming=data.calendar_items.filter(i=>!i.completed&&Date.parse(i.due_at)>Date.now()).sort((a,b)=>a.due_at.localeCompare(b.due_at));const internships=data.internships.filter(i=>(!i.university_id||i.university_id===universityId)&&i.status!=='closed'&&(!i.deadline||Date.parse(i.deadline)>Date.now())),listings=data.listings.filter(i=>i.university_id===universityId&&i.kind==='market'&&i.status==='active').slice(0,2),clubs=data.clubs.filter(c=>c.university_id===universityId),events=data.club_events.filter(e=>clubs.some(c=>c.id===e.club_id)&&data.club_follows.some(f=>f.club_id===e.club_id)&&Date.parse(e.starts_at)>Date.now());return <>
<div className="dashboard-heading"><div><div className="eyebrow"><Sun size={16}/> YENİ BİR GÜN, YENİ İHTİMALLER</div><h1>İyi ki geldin, {profile?.display_name?.split(' ')[0]||'arkadaşım'} <span className="hello-dot">✦</span></h1><p>Kampüsünde olup bitenler ve bugününü kolaylaştıracak küçük şeyler.</p></div><div className="today-label"><CalendarDays size={16}/>{new Date().toLocaleDateString('tr-TR',{timeZone:'Europe/Istanbul',day:'numeric',month:'long',weekday:'long'})}</div></div>
<section className="welcome-banner"><div><Badge tone="banner-badge">{uni?.short_name||'KAMPÜSÜN'} · SENİN ALANIN</Badge><h2>Kampüs hayatına<br/>biraz yer aç.</h2><p>Yeni arkadaşlar, paylaşılan notlar ve bir sonraki fırsat.<br/>Hepsi burada, bir arada.</p><Link to={base+'/kulupler'}>Kampüsü keşfet <ArrowUpRight size={17}/></Link></div><img src="/campus.png" alt="Öğrencilerin bir araya geldiği kampüs avlusu"/><div className="banner-label"><span className="icon-tile yellow"><Users size={21}/></span><div><strong>Birlikte daha güzel.</strong><span>Kendi topluluğunu bul.</span></div></div></section>
<div className="stats-grid">{[{icon:CalendarDays,color:'blue',label:'Yaklaşan tarihler',value:String(upcoming.length).padStart(2,'0'),note:'Takvimine bir göz at',path:'takvim'},{icon:Wallet,color:'green',label:'Bu ay kalan bütçen',value:money(budget.balance),note:budget.income?'Gelir ve giderlerine göre':'İlk gelirini ekleyerek başla',path:'butce'},{icon:Users,color:'pink',label:'Kulüplerinden etkinlikler',value:String(events.length).padStart(2,'0'),note:'Birlikte yeni şeyler dene',path:'kulupler'},{icon:BriefcaseBusiness,color:'yellow',label:'Staj fırsatları',value:String(internships.length).padStart(2,'0'),note:demo?'Kaynaklı fırsatları keşfet':'Kariyerine bir adım',path:'stajlar'}].map(s=><Link to={base+'/'+s.path} className="stat-card" key={s.path}><div><span className={'icon-tile '+s.color}><s.icon size={20}/></span><ArrowUpRight size={17}/></div><span className="stat-label">{s.label}</span><strong>{s.value}</strong><p>{s.note}</p></Link>)}</div>
<div className="dashboard-grid"><div className="dashboard-left"><section className="panel"><div className="panel-heading"><h2>Yaklaşanlar</h2><Link to={base+'/takvim'}>Takvimim <ArrowUpRight size={15}/></Link></div>{upcoming.length?upcoming.slice(0,3).map(item=><Link className="event-row" to={base+'/takvim'} key={item.id}><div className={'date-tile '+(item.kind==='exam'?'pink':'blue')}><strong>{new Date(item.due_at).toLocaleDateString('tr-TR',{timeZone:'Europe/Istanbul',day:'2-digit'})}</strong><span>{new Date(item.due_at).toLocaleDateString('tr-TR',{timeZone:'Europe/Istanbul',month:'short'})}</span></div><div><h3>{item.title}</h3><span><Clock size={13}/>{trDate(item.due_at,true)}</span></div><Badge tone={item.kind==='exam'?'pink':'blue'}>{item.kind==='exam'?'Sınav':item.kind==='deadline'?'Teslim':'Etkinlik'}</Badge></Link>):<Empty title="Takvimin ferah görünüyor." text="Bir sınav veya teslim tarihi ekleyerek başla."/>}<Link className="dashed-add" to={base+'/takvim?yeni=1'}><Plus size={17}/> Takvimime ekle</Link></section>
<section className="panel"><div className="panel-heading"><h2>Kampüs pazarı</h2><Link to={base+'/pazar'}>Tüm ilanlar <ArrowUpRight size={15}/></Link></div><div className="mini-listings">{listings.map((item,i)=><Link to={base+'/pazar?ilan='+item.id} key={item.id}><div className={'mini-product '+(i?'blue':'yellow')}>{i?<BookOpen size={42} strokeWidth={1.3}/>:<ShoppingBag size={42} strokeWidth={1.3}/>}</div><div><Example value={item.is_example}/><h3>{item.title}</h3><span>{item.district}</span><strong>{money(item.price_kurus)}</strong></div></Link>)}</div>{!listings.length&&<Empty title="Yeni fırsatlar için yer var."/>}</section></div>
<div className="dashboard-right"><section className="panel crowd-panel"><div className="panel-heading"><h2>Kampüs şu an</h2><Link to={base+'/yogunluk'} aria-label="Yoğunluk detayları"><ArrowUpRight size={17}/></Link></div>{data.crowd_locations.filter(l=>l.university_id===universityId).map(l=>{const summary=crowdSummary(data.crowd_reports,l.id);return <div className="crowd-mini" key={l.id}><span className={'icon-tile '+(l.kind==='library'?'blue':'yellow')}>{l.kind==='library'?<Library size={20}/>:<Utensils size={20}/>}</span><div><strong>{l.name}</strong><p>{summary.count?summary.count+' öğrencinin son bildirimi':'Güncel bildirim yok'}</p></div><Badge tone={summary.level===1?'green':summary.level===3?'pink':'yellow'}>{summary.level===1?'Sakin':summary.level===2?'Orta':summary.level===3?'Kalabalık':'—'}</Badge></div>})}<p className="panel-footnote">{demo?'Örnek bildirimler · ':'Öğrenci bildirimleri · '}Son 1 saat</p><Link className="button secondary small full" to={base+'/yogunluk'}>Sen de durum bildir <ArrowRight size={15}/></Link></section>
<section className="quick-panel"><span className="eyebrow">KÜÇÜK ADIMLAR</span><h2>Bugün ne yapalım?</h2>{[{icon:BookOpen,title:'Bir not paylaş',sub:'Bilgi paylaştıkça çoğalır.',path:'notlar?yeni=1'},{icon:Wallet,title:'Harcamalarını ekle',sub:'Ay sonuna hazırlıklı ol.',path:'butce?yeni=1'},{icon:Users,title:'Oda arkadaşını bul',sub:'Aynı evde, aynı frekansta.',path:'oda-arkadasi'}].map(q=><Link key={q.path} to={base+'/'+q.path}><span className="quick-icon"><q.icon size={20}/></span><div><strong>{q.title}</strong><p>{q.sub}</p></div><ArrowUpRight size={17}/></Link>)}</section></div></div>
<div className="bottom-note"><CheckCircle2 size={16}/><span>Kendi hızında, kendi kampüsünde. Her şeyi aynı anda çözmek zorunda değilsin.</span></div>
</>}
