import {useEffect,useState} from 'react'
import {Plus,Bookmark,MapPin,BriefcaseBusiness,Clock,ArrowUpRight,Pencil,Check,RefreshCw} from 'lucide-react'
import {useStore,errorText} from '../lib/store'
import {dataApi} from '../services/data'
import {PageHead,SearchBox,Badge,Example,Empty,Modal,Field,ErrorBox,Submit,useFormAction,str} from '../components/ui'
import {safeExternalUrl,trDate,localInputToUTC,utcToLocalInput} from '@kampuskit/shared/domain'
import type {Internship} from '@kampuskit/shared/types'

export function InternshipsPage(){
 const s=useStore(),[query,setQuery]=useState(''),[field,setField]=useState(''),[mode,setMode]=useState(''),[region,setRegion]=useState('turkey'),[sourceKind,setSourceKind]=useState(''),[savedOnly,setSavedOnly]=useState(false),[mine,setMine]=useState(false),[selected,setSelected]=useState<string|null>(null),[form,setForm]=useState<Internship|'new'|null>(null),[syncing,setSyncing]=useState(false)
 useEffect(()=>{setSelected(null);setField('');setMode('')},[s.universityId])
 const source=s.data.internships.filter(i=>!i.university_id||i.university_id===s.universityId)
 const items=source.filter(i=>(mine?i.user_id===s.userId:i.status!=='closed')&&(!i.deadline||Date.parse(i.deadline)>Date.now()||mine)&&(!field||i.field===field)&&(!mode||i.work_mode===mode)&&(region==='all'||/türkiye|turkey|istanbul|İstanbul|ankara|izmir|İzmir/i.test(i.location))&&(!sourceKind||(i.is_example?'example':i.source_kind||'student')===sourceKind)&&(!savedOnly||s.data.saved_internships.some(x=>x.internship_id===i.id))&&(i.title+' '+i.company).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))).sort((a,b)=>Number(a.is_example)-Number(b.is_example))
 const item=source.find(i=>i.id===selected)
 async function sync(){if(s.demo){s.notify('Kaynakları yenilemek için hesabına giriş yap.');return}setSyncing(true);try{const result=await dataApi.syncInternships();await s.refresh();const runs=result.sources;s.notify(runs.some(r=>r.status==='failed')?'Bazı kaynaklara ulaşılamadı. Mevcut ilanlar korundu.':runs.every(r=>r.status==='cooldown')?'Kaynaklar son bir saat içinde kontrol edildi.':'Staj kaynakları güncellendi.')}catch(e){s.notify(errorText(e))}finally{setSyncing(false)}}
 return <><PageHead eyebrow="BİR SONRAKİ ADIMIN" title="Staj fırsatları" description="Şirket kaynaklarından toplanan fırsatlar ve öğrencilerin paylaştığı ilanlar."><button className="button" onClick={()=>setForm('new')}><Plus size={18}/>Staj ilanı ekle</button></PageHead>
 <div className="filter-bar"><SearchBox value={query} onChange={setQuery} placeholder="Pozisyon veya şirket ara"/><select aria-label="Staj bölgesi" value={region} onChange={e=>setRegion(e.target.value)}><option value="turkey">Türkiye</option><option value="all">Tüm ülkeler</option></select><select aria-label="Staj alanı" value={field} onChange={e=>setField(e.target.value)}><option value="">Alan · Tümü</option>{[...new Set(source.map(i=>i.field))].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Çalışma biçimi" value={mode} onChange={e=>setMode(e.target.value)}><option value="">Çalışma biçimi · Tümü</option>{[...new Set(source.map(i=>i.work_mode))].map(v=><option key={v}>{v}</option>)}</select><select aria-label="İlan kaynağı" value={sourceKind} onChange={e=>setSourceKind(e.target.value)}><option value="">Bütün kaynaklar</option><option value="import">Şirket kaynağı</option><option value="student">Öğrenci paylaşımı</option><option value="example">Örnek ilanlar</option></select></div>
 <div className="discovery-toolbar"><span>{items.length} ilan</span><button className={'filter-toggle '+(savedOnly?'selected':'')} onClick={()=>setSavedOnly(!savedOnly)}><Bookmark size={16}/>Kaydettiklerim</button><button className={'filter-toggle '+(mine?'selected':'')} onClick={()=>setMine(!mine)}>Eklediklerim</button><button className="text-button" disabled={syncing} onClick={()=>void sync()}><RefreshCw size={15}/>{syncing?'Kaynaklar kontrol ediliyor…':'Kaynakları yenile'}</button></div>
 <div className="job-list">{items.map((i,index)=>{const saved=s.data.saved_internships.find(x=>x.internship_id===i.id);return <article className="panel job-card" key={i.id}><span className={'company-icon '+['blue','pink','yellow'][index%3]}>{i.company.slice(0,1)}</span><div className="job-main"><div className="job-eyebrow">{i.company}<Example value={i.is_example}/>{!i.is_example&&<Badge tone={i.source_kind==='import'?'green':'blue'}>{i.source_kind==='import'?'Şirket kaynağı':'Öğrenci paylaşımı'}</Badge>}{i.status==='closed'&&<Badge tone="pink">Kapalı</Badge>}</div><button className="plain-button job-title" onClick={()=>setSelected(i.id)}>{i.title}</button><div className="job-meta"><span><MapPin size={14}/>{i.location}</span><span><BriefcaseBusiness size={14}/>{i.work_mode}</span><span><Clock size={14}/>{i.deadline?'Son tarih: '+trDate(i.deadline):'Son tarih belirtilmemiş'}</span></div>{i.fetched_at&&<p className="source-timestamp">Kaynak kontrolü: {trDate(i.fetched_at,true)}{Date.now()-Date.parse(i.fetched_at)>24*3600000?' · Yeniden kontrol edilmeli':''}</p>}</div><div className="job-actions"><button className={'icon-button '+(saved?'saved':'')} aria-label={saved?'Staj kaydını kaldır':'Stajı kaydet'} onClick={()=>void (saved?s.remove('saved_internships',saved.id):s.save('saved_internships',{internship_id:i.id})).catch(e=>s.notify(errorText(e)))}><Bookmark size={20} fill={saved?'currentColor':'none'}/></button><button className="button secondary small" onClick={()=>setSelected(i.id)}>İncele <ArrowUpRight size={16}/></button></div></article>})}</div>
 {!items.length&&<Empty title="Bu filtrelerde açık ilan bulunamadı." text="Tüm ülkeleri seçebilir, filtreleri genişletebilir veya bir staj fırsatı paylaşabilirsin."/>}
 <p className="section-footnote">Başvurular kaynak sitede yapılır. Yurt dışı ve uzaktan ilanlarda çalışma izni ve konum şartlarını kaynaktan kontrol et.</p>
 {item&&<Modal title={item.title} onClose={()=>setSelected(null)}><div className="detail-body"><Badge>{item.company}</Badge><p className="prose">{item.description}</p><p className="muted">{item.location} · {item.work_mode} · {item.field}</p>{item.source_name&&<p className="source-timestamp">Kaynak: {item.source_name}</p>}{item.is_example?<div className="setup-notice">Bu ilan örnektir. Gerçek bir başvuru alınmaz.</div>:item.source_url&&safeExternalUrl(item.source_url)&&<a className="button" href={safeExternalUrl(item.source_url)!} target="_blank" rel="noopener noreferrer">Kaynakta başvur <ArrowUpRight size={17}/></a>}{item.user_id===s.userId&&!item.is_example&&<div className="row-actions"><button className="button secondary small" onClick={()=>{setForm(item);setSelected(null)}}><Pencil size={15}/>Düzenle</button><button className="button secondary small" onClick={()=>void s.save('internships',{status:item.status==='closed'?'active':'closed'},item.id).catch(e=>s.notify(errorText(e)))}><Check size={15}/>{item.status==='closed'?'Yeniden aç':'İlanı kapat'}</button></div>}</div></Modal>}
 {form&&<InternshipForm job={form==='new'?null:form} onClose={()=>setForm(null)}/>}</>
}
function InternshipForm({job,onClose}:{job:Internship|null;onClose:()=>void}){
 const s=useStore(),{run,busy,error}=useFormAction(onClose)
 return <Modal title={job?'Staj ilanını düzenle':'Bir staj fırsatı paylaş'} onClose={onClose} wide><form onSubmit={e=>run(e,async f=>{const link=safeExternalUrl(str(f,'source_url'));if(!link)throw new Error('Geçerli bir başvuru bağlantısı gir.');const deadline=str(f,'deadline');const row={title:str(f,'title'),company:str(f,'company'),field:str(f,'field'),location:str(f,'location'),work_mode:str(f,'work_mode'),description:str(f,'description'),source_url:link,deadline:deadline?localInputToUTC(deadline):null};if(row.deadline&&Date.parse(row.deadline)<=Date.now())throw new Error('Son başvuru tarihi gelecekte olmalı.');await s.save('internships',job?row:{...row,university_id:s.universityId},job?.id)})}><div className="form-grid"><Field label="Pozisyon" wide><input name="title" required minLength={3} maxLength={150} defaultValue={job?.title}/></Field><Field label="Şirket"><input name="company" required maxLength={100} defaultValue={job?.company}/></Field><Field label="Alan"><select name="field" defaultValue={job?.field}>{['Yazılım','Tasarım','Pazarlama','Veri & Araştırma','İnsan Kaynakları','İşletme','Diğer'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Şehir / ülke"><input name="location" required maxLength={150} defaultValue={job?.location} placeholder="İstanbul, Türkiye"/></Field><Field label="Çalışma biçimi"><select name="work_mode" defaultValue={job?.work_mode}>{['Belirtilmemiş','Ofiste','Hibrit','Uzaktan'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Kaynak / başvuru bağlantısı" wide><input name="source_url" type="url" required defaultValue={job?.source_url||''} placeholder="https://…"/></Field><Field label="Son başvuru tarihi · isteğe bağlı" wide><input name="deadline" type="datetime-local" defaultValue={job?.deadline?utcToLocalInput(job.deadline):''}/><small>Türkiye saati. Kaynakta tarih yoksa boş bırak.</small></Field><Field label="Açıklaman" wide><textarea name="description" required maxLength={3000} rows={4} defaultValue={job?.description}/></Field></div><ErrorBox message={error}/><div className="form-footer"><span>İlan, öğrenci paylaşımı olarak görünür.</span><Submit busy={busy} label="İlanı kaydet"/></div></form></Modal>
}
