import {useEffect,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import {Plus,MapPin,ArrowUpRight,Star,Coffee,Pencil} from 'lucide-react'
import {useStore,errorText} from '../lib/store'
import {PageHead,SearchBox,Badge,Example,Empty,Modal,Field,ErrorBox,Submit,useFormAction,str} from '../components/ui'
import {CampusMap} from '../components/campus-map'
import {mapsConfigured,nearbyPlaces} from '../lib/maps'
import type {GooglePlace} from '../lib/maps'
import {distanceMeters,priceLabel,studentScore} from '../lib/place-ranking'
import {money,toKurus,safeExternalUrl,dateKey} from '@kampuskit/shared/domain'
import type {Campus,Place} from '@kampuskit/shared/types'

export function PlacesPage(){
 const s=useStore(),[tab,setTab]=useState('google')
 return <><PageHead eyebrow="KAMPÜS ÇEVRESİNDE" title="Bir mola verelim." description="Yakındaki mekanları karşılaştır, öğrencilerin deneyimlerini keşfet."/>
 <div className="filter-bar"><div className="tabs"><button className={tab==='google'?'active':''} onClick={()=>setTab('google')}>Google Maps’te keşfet</button><button className={tab==='students'?'active':''} onClick={()=>setTab('students')}>Öğrenci önerileri</button></div></div>
 {tab==='google'?<GoogleDiscovery key={s.universityId}/>:<StudentPlaces key={s.universityId}/>}
 <p className="section-footnote"><Link to="/gizlilik">Gizlilik</Link> · <Link to="/kosullar">Kullanım koşulları</Link></p></>
}
function GoogleDiscovery(){
 const s=useStore(),campuses=s.data.campuses.filter(c=>c.university_id===s.universityId),[campusId,setCampus]=useState(campuses[0]?.id||''),[category,setCategory]=useState('cafe'),[radius,setRadius]=useState(3000),[maxPrice,setMaxPrice]=useState(2),[unknown,setUnknown]=useState(true),[items,setItems]=useState<GooglePlace[]>([]),[selected,setSelected]=useState<GooglePlace|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[searched,setSearched]=useState(false),[checked,setChecked]=useState(''),sequence=useRef(0)
 const campus=campuses.find(c=>c.id===campusId),center=campus?.latitude!=null&&campus.longitude!=null?{lat:campus.latitude,lng:campus.longitude}:null
 useEffect(()=>()=>{sequence.current++},[])
 function reset(){sequence.current++;setBusy(false);setItems([]);setSelected(null);setSearched(false);setError('')}
 async function search(){if(!center)return;const request=++sequence.current;setBusy(true);setError('');try{const results=await nearbyPlaces(center,radius,category);if(request!==sequence.current)return;setItems(results);setSearched(true);setChecked(new Date().toLocaleTimeString('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'}))}catch(e){if(request===sequence.current){setItems([]);setSearched(false);setError(errorText(e))}}finally{if(request===sequence.current)setBusy(false)}}
 const ranked=items.filter(p=>p.price===null?unknown:p.price<=maxPrice).map(p=>({...p,distance:distanceMeters(center!,p.point),score:studentScore(p.price,distanceMeters(center!,p.point),radius,p.rating,p.count)})).sort((a,b)=>(b.score??-1)-(a.score??-1)||a.distance-b.distance)
 return <><div className="filter-bar"><select aria-label="Mekan kampüsü" value={campusId} onChange={e=>{reset();setCampus(e.target.value)}}>{campuses.map(c=><option key={c.id} value={c.id}>{c.name} Kampüsü</option>)}</select><select aria-label="Google mekan kategorisi" value={category} onChange={e=>{reset();setCategory(e.target.value)}}><option value="cafe">Kafe</option><option value="restaurant">Yemek</option><option value="library">Kütüphane</option></select><select aria-label="Arama yarıçapı" value={radius} onChange={e=>{reset();setRadius(Number(e.target.value))}}>{[1000,2000,3000,5000].map(n=><option key={n} value={n}>{n/1000} km çevresi</option>)}</select><select aria-label="En yüksek fiyat seviyesi" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}><option value={1}>₺ · En ekonomik</option><option value={2}>₺₺ · Orta ve altı</option><option value={4}>Tüm fiyat seviyeleri</option></select><button className="button" disabled={!center||busy||!mapsConfigured} onClick={()=>void search()}>{busy?'Mekanlar aranıyor…':'Yakınımda keşfet'}</button></div>
 <label className="discovery-check"><input type="checkbox" checked={unknown} onChange={e=>setUnknown(e.target.checked)}/>Fiyat bilgisi olmayanları da göster</label>
 <ErrorBox message={error}/>{!mapsConfigured&&<p className="setup-notice">Google Maps bağlantısı henüz kurulmadı. Öğrenci önerilerini keşfedebilirsin.</p>}{!center&&<Empty title="Bu kampüsün konumu henüz eklenmedi." text="Öğrenci önerileri sekmesindeki mekanlara göz atabilirsin."/>}
 {center&&mapsConfigured&&<div className="places-map-layout"><section className="panel map-panel"><CampusMap center={center} label={(campus?.name||'')+' Kampüsü'}/><p className="section-footnote">Kampüs referans noktasına kuş uçuşu uzaklık kullanılır.{campus?.source_url&&<> <a href={campus.source_url} target="_blank" rel="noreferrer">Konum kaynağı</a></>}</p></section><section className="panel ranking-explainer"><Badge tone="yellow">Sıralama nasıl çalışır?</Badge><h2>Bütçene ve kampüsüne göre.</h2><p>Fiyat %40, yakınlık %35, Google puanı %25. Az yorumlu mekanların puanını dengeleriz. Fiyatı veya puanı bilinmeyenlere skor vermeyiz.</p><p>Skor, bu aramada karşılaştırma içindir. Gerçek menü fiyatını ve öğrenci indirimini mekandan kontrol et.</p>{searched&&<strong>{ranked.length} sonuç · {checked}’te kontrol edildi</strong>}<p className="muted">Google Maps en yakın 20 sonucu getirir; çevredeki tüm mekanları kapsamaz.</p></section></div>}
 {searched&&<div className="content-grid">{ranked.map(p=><button className="panel live-place" key={p.id} onClick={()=>setSelected(p)}><div className="card-top"><span className="icon-tile yellow"><Coffee size={24}/></span><Badge tone={p.score===null?'blue':'green'}>{p.score===null?'Skor için eksik bilgi':p.score+'/100 uygunluk'}</Badge></div><h2>{p.name}</h2><p><MapPin size={14}/>{(p.distance/1000).toFixed(1)} km · {p.address}</p><div className="place-rating"><strong>{priceLabel(p.price)}</strong><span><Star size={15}/>{p.rating??'Puan yok'} ({p.count})</span></div><span className="text-button">Haritada incele <ArrowUpRight size={16}/></span></button>)}</div>}
 {searched&&ranked.flatMap(p=>p.attributions.map((a,i)=><p className="source-timestamp" key={p.id+i}>{p.name} · {safeExternalUrl(a.url||'')?<a href={safeExternalUrl(a.url!)!} target="_blank" rel="noreferrer">{a.name}</a>:a.name}</p>))}
 {searched&&!ranked.length&&<Empty title="Bu ölçütlerde mekan bulunamadı." text="Fiyat filtresini genişletebilir, yarıçapı değiştirebilir veya başka bir kategori arayabilirsin."/>}
 {selected&&<Modal title={selected.name} onClose={()=>setSelected(null)} wide><div className="detail-body"><CampusMap center={selected.point} label={selected.name} zoom={17}/><p>{selected.address}</p><p><strong>{priceLabel(selected.price)}</strong> · Google puanı: {selected.rating??'Yok'} / 5 · {selected.count} değerlendirme</p><a className="button" href={safeExternalUrl(selected.url)||undefined} target="_blank" rel="noreferrer">Google Maps’te aç <ArrowUpRight size={16}/></a>{selected.attributions.map((a,i)=><p className="source-timestamp" key={i}>{safeExternalUrl(a.url||'')?<a href={safeExternalUrl(a.url!)!} target="_blank" rel="noreferrer">{a.name}</a>:a.name}</p>)}</div></Modal>}
 </>
}
function StudentPlaces(){
 const s=useStore(),[query,setQuery]=useState(''),[price,setPrice]=useState(''),[category,setCategory]=useState(''),[selected,setSelected]=useState<string|null>(null),[form,setForm]=useState<Place|'new'|null>(null)
 const places=s.data.places.filter(p=>p.university_id===s.universityId&&(!price||p.price_level<=Number(price))&&(!category||p.category===category)&&(p.name+' '+p.district).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))),place=s.data.places.find(p=>p.id===selected)
 return <><div className="filter-bar"><SearchBox value={query} onChange={setQuery} placeholder="Mekan veya semt ara"/><select aria-label="Öneri kategorisi" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Tüm kategoriler</option>{['Kafe','Yemek','Çalışma'].map(c=><option key={c}>{c}</option>)}</select><select aria-label="Öneri fiyat seviyesi" value={price} onChange={e=>setPrice(e.target.value)}><option value="">Tüm fiyatlar</option><option value="1">₺ · Ekonomik</option><option value="2">₺₺ · Orta ve altı</option></select><button className="button" onClick={()=>setForm('new')}><Plus size={18}/>Mekan öner</button></div><div className="content-grid">{places.map(p=>{const reviews=s.data.reviews.filter(r=>r.place_id===p.id);return <button className="panel live-place" key={p.id} onClick={()=>setSelected(p.id)}><div className="card-top"><Badge tone="yellow">{p.category}</Badge><Example value={p.is_example}/></div><h2>{p.name}</h2><p>{p.district} · {'₺'.repeat(p.price_level)}</p><p>{p.description}</p><div className="place-rating"><span>{reviews.length?(reviews.reduce((a,r)=>a+r.rating,0)/reviews.length).toFixed(1)+'/5':'Henüz puan yok'} · {reviews.length} öğrenci</span><ArrowUpRight size={18}/></div>{p.meal_price_kurus&&<p>Öğrencinin bildirdiği fiyat: {money(p.meal_price_kurus)} · {p.price_observed_on}</p>}</button>})}</div>{!places.length&&<Empty title="Bu aramada öneri yok." text="Bildiğin öğrenci dostu bir mekanı paylaşabilirsin."/>}
 {place&&<StudentDetail place={place} onClose={()=>setSelected(null)} onEdit={()=>{setForm(place);setSelected(null)}}/>}{form&&<PlaceForm place={form==='new'?null:form} onClose={()=>setForm(null)} campuses={s.data.campuses.filter(c=>c.university_id===s.universityId)}/>}</>
}
function StudentDetail({place,onClose,onEdit}:{place:Place;onClose:()=>void;onEdit:()=>void}){
 const s=useStore(),reviews=s.data.reviews.filter(r=>r.place_id===place.id),mine=reviews.find(r=>r.user_id===s.userId),{run,busy,error}=useFormAction()
 const mapsUrl=safeExternalUrl(place.maps_url||'')||(!place.is_example?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(place.name+' '+(place.address||place.district)+' İstanbul'):null)
 return <Modal title={place.name} onClose={onClose}><div className="detail-body"><Example value={place.is_example}/><p className="prose">{place.description}</p><p>{place.address||place.district}</p>{place.latitude!=null&&place.longitude!=null&&mapsConfigured&&<CampusMap center={{lat:place.latitude,lng:place.longitude}} label={place.name}/>}{mapsUrl&&<a className="text-button" href={mapsUrl} target="_blank" rel="noreferrer">Google Maps’te aç <ArrowUpRight size={16}/></a>}{place.user_id===s.userId&&!place.is_example&&<button className="button secondary small" onClick={onEdit}><Pencil size={15}/>Önerimi düzenle</button>}<h3>Öğrenciler ne diyor?</h3>{reviews.map(r=><div className="reply" key={r.id}><strong>{'★'.repeat(r.rating)} · {s.data.members.find(m=>m.id===r.user_id)?.display_name||'Öğrenci'}</strong><p>{r.body}</p></div>)}{!reviews.length&&<p className="muted">İlk deneyimi sen paylaş.</p>}<form onSubmit={e=>run(e,async f=>s.save('reviews',{place_id:place.id,rating:Number(str(f,'rating')),body:str(f,'body')},mine?.id))}><Field label="Senin puanın"><select name="rating" defaultValue={mine?.rating||5}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n}/5</option>)}</select></Field><Field label="Deneyimin"><textarea name="body" required maxLength={2000} rows={3} defaultValue={mine?.body} placeholder="Menü fiyatı, ortam, çalışmaya uygunluk…"/></Field><ErrorBox message={error}/><Submit busy={busy} label={mine?'Yorumumu güncelle':'Değerlendir'}/></form></div></Modal>
}
function PlaceForm({place,onClose,campuses}:{place:Place|null;onClose:()=>void;campuses:Campus[]}){
 const s=useStore(),{run,busy,error}=useFormAction(onClose)
 return <Modal title={place?'Önerimi düzenle':'Öğrenci dostu bir mekan öner'} onClose={onClose} wide><form onSubmit={e=>run(e,async f=>{const raw=str(f,'maps_url'),maps=raw?safeExternalUrl(raw):null;if(raw&&(!maps||!/^https:\/\/(www\.)?(google\.com|maps\.google\.com|maps\.app\.goo\.gl|goo\.gl)\//.test(maps)))throw new Error('Google Maps paylaşım bağlantısını gir.');const amount=str(f,'meal_price'),observed=str(f,'price_observed_on');if(amount&&!observed)throw new Error('Fiyatı gördüğün tarihi ekle.');if(observed>dateKey(new Date()))throw new Error('Fiyat gözlem tarihi gelecekte olamaz.');const row={campus_id:str(f,'campus_id'),name:str(f,'name'),category:str(f,'category'),price_level:Number(str(f,'price_level')),district:str(f,'district'),address:str(f,'address'),description:str(f,'description'),symbol:str(f,'category')==='Kafe'?'coffee':str(f,'category')==='Çalışma'?'book':'utensils',maps_url:maps,meal_price_kurus:amount?toKurus(amount):null,price_observed_on:amount?observed:null};await s.save('places',place?row:{...row,university_id:s.universityId},place?.id)})}><div className="form-grid"><Field label="Mekan adı" wide><input name="name" required maxLength={150} defaultValue={place?.name}/></Field><Field label="Kampüs"><select name="campus_id" defaultValue={place?.campus_id||campuses[0]?.id}>{campuses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Kategori"><select name="category" defaultValue={place?.category}>{['Kafe','Yemek','Çalışma'].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Fiyat seviyesi"><select name="price_level" defaultValue={place?.price_level||1}><option value="1">₺ · Ekonomik</option><option value="2">₺₺ · Orta</option><option value="3">₺₺₺ · Yüksek</option></select></Field><Field label="Semt"><input name="district" required maxLength={100} defaultValue={place?.district}/></Field><Field label="Adres" wide><input name="address" maxLength={500} defaultValue={place?.address}/></Field><Field label="Google Maps paylaşım bağlantısı · isteğe bağlı" wide><input name="maps_url" type="url" defaultValue={place?.maps_url||''}/></Field><Field label="Gördüğün menü / ürün fiyatı · TL"><input name="meal_price" inputMode="decimal" defaultValue={place?.meal_price_kurus?place.meal_price_kurus/100:''}/></Field><Field label="Fiyatı gördüğün tarih"><input name="price_observed_on" type="date" max={dateKey(new Date())} defaultValue={place?.price_observed_on||''}/></Field><Field label="Neden öneriyorsun?" wide><textarea name="description" required maxLength={2000} rows={4} defaultValue={place?.description} placeholder="Kendi deneyimini yaz. Fiyat verdiysen hangi ürün olduğunu da belirt."/></Field></div><ErrorBox message={error}/><div className="form-footer"><Submit busy={busy} label="Önerimi kaydet"/></div></form></Modal>
}
