import type {BudgetEntry,CalendarItem,CrowdReport} from './types.ts'
export const money=(kurus:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:kurus%100===0?0:2}).format(kurus/100)
export function toKurus(raw:string){const normalized=raw.trim().replace(',','.');if(!/^\d+(\.\d{1,2})?$/.test(normalized))throw new Error('Tutarı en fazla iki ondalık basamakla gir.');const value=Math.round(Number(normalized)*100);if(!Number.isSafeInteger(value)||value<=0||value>10000000000)throw new Error('Geçerli, sıfırdan büyük bir tutar gir.');return value}
export const trDate=(value:string,withTime=false)=>new Date(value).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul',day:'numeric',month:'long',...(withTime?{hour:'2-digit',minute:'2-digit'}:{})})
export const dateKey=(date=new Date())=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)
export const monthKey=(date=new Date())=>dateKey(date).slice(0,7)
export function budgetSummary(entries:BudgetEntry[],month:string){const selected=entries.filter(e=>e.occurred_on.startsWith(month));const income=selected.filter(e=>e.type==='income').reduce((s,e)=>s+e.amount_kurus,0);const expense=selected.filter(e=>e.type==='expense').reduce((s,e)=>s+e.amount_kurus,0);return{income,expense,balance:income-expense,entries:selected}}
export function crowdSummary(reports:CrowdReport[],location:string,now=Date.now()){
const latest=new Map<string,CrowdReport>();for(const r of reports){const t=Date.parse(r.created_at);if(r.location_id!==location||t>now||t<now-3600000)continue;const old=latest.get(r.user_id);if(!old||Date.parse(old.created_at)<t)latest.set(r.user_id,r)}
const current=[...latest.values()];const counts=[1,2,3].map(level=>current.filter(r=>r.level===level).length);return{count:current.length,counts,level:current.length?Math.round(current.reduce((s,r)=>s+r.level,0)/current.length):null,last:current.length?new Date(Math.max(...current.map(r=>Date.parse(r.created_at)))).toISOString():null}}
export function isReminderDue(item:CalendarItem,now=Date.now()){const due=Date.parse(item.due_at);return !item.completed&&due>now&&due-item.reminder_minutes*60000<=now}
export function safeExternalUrl(raw:string){try{const u=new URL(raw);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}}
export function localInputToUTC(value:string){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value))throw new Error('Tarih ve saat seç.');const d=new Date(value+':00+03:00');if(Number.isNaN(d.getTime()))throw new Error('Geçerli bir tarih seç.');return d.toISOString()}
export function utcToLocalInput(value:string){const date=new Date(Date.parse(value)+3*3600000);return date.toISOString().slice(0,16)}
export function validateUpload(file:File,bucket:'notes'|'listing-images'){const allowed=bucket==='notes'?['application/pdf']:['image/jpeg','image/png','image/webp'];const max=(bucket==='notes'?10:5)*1024*1024;if(!allowed.includes(file.type))throw new Error(bucket==='notes'?'Yalnızca PDF yükleyebilirsin.':'JPEG, PNG veya WebP görsel seç.');if(file.size>max)throw new Error('Dosya en fazla '+(bucket==='notes'?10:5)+' MB olabilir.')}
