import type {DatabaseState} from './types.ts'
export function enrichExamples(d:DatabaseState,id:(n:number)=>string,at:(hours:number)=>string){
 const notes=[
 ['Türev · Zincir kuralı',1,'Bileşke fonksiyonun türevi dış fonksiyonun türevi ile iç fonksiyonun türevinin çarpımıdır. f(x)=(3x+1)² için f′(x)=2(3x+1)×3. Önce hangi ifadenin iç fonksiyon olduğunu belirle; iç türevi unutma.'],
 ['İntegral · Değişken değiştirme',1,'∫2x cos(x²) dx için u=x² seç. du=2x dx olduğundan integral ∫cos(u) du=sin(u)+C olur. Son adımda u yerine x² yaz. Belirli integralde sınırları da yeni değişkene dönüştür.'],
 ['Matrisler · Çarpma sırası',1,'A, m×n ve B, n×p boyutundaysa AB, m×p olur. (AB)ij, A’nın i. satırı ile B’nin j. sütununun iç çarpımıdır. Genellikle AB≠BA. Boyut kontrolünü hesaplamadan önce yap.'],
 ['Seriler · Geometrik toplam',1,'|r|<1 olduğunda a+ar+ar²+…=a/(1−r). Sonlu toplam a(1−rⁿ)/(1−r) biçimindedir. r=1 durumunu ayrı ele al. Sonsuz toplam formülünü |r|≥1 durumunda kullanma.'],
 ['Python · Liste ve sözlük seçimi',2,'Sıralı öğeler için liste, bir anahtar üzerinden erişim için sözlük kullan. Bir öğrenci numarasından ada erişeceksen sözlük doğal bir modeldir. Liste üzerinde arama genellikle O(n), sözlükte ortalama anahtar erişimi O(1) olur.'],
 ['Git · Küçük commit alışkanlığı',2,'Önce git status ile değişiklikleri incele. İlgili dosyaları ekle, git diff --staged ile kontrol et ve değişikliğin amacını anlatan bir commit yaz. Gizli anahtarlar ve .env dosyaları versiyon kontrolüne girmemeli.'],
 ['SQL · JOIN ve NULL',2,'INNER JOIN yalnızca eşleşen kayıtları getirir. LEFT JOIN soldaki tüm kayıtları korur; eşleşmeyen sağ alanlar NULL olur. NULL karşılaştırması için = NULL yerine IS NULL kullan. LEFT JOIN sonrası sağ tabloya WHERE filtresi koymanın etkisini düşün.'],
 ['Algoritma · İkili arama',2,'İkili arama sıralı veride çalışır. Ortadaki değerle hedefi karşılaştırıp aralığın yarısını elersin. Her adımda aralık yarıya indiği için karmaşıklık O(log n). Sınırların dahil olup olmadığını kod boyunca tutarlı tut.'],
 ['Enerji · İş ve kinetik enerji',3,'Net iş, kinetik enerjideki değişime eşittir: Wnet=ΔK. K=mv²/2. Sabit kuvvetin işi F·s=Fs cosθ. Hızın karesi kullanıldığı için hız ikiye katlanınca kinetik enerji dört katına çıkar.'],
 ['Momentum · Çarpışma çözümü',3,'Toplam dış itki ihmal edilebiliyorsa momentum korunur. Esnek çarpışmada kinetik enerji de korunur; her çarpışmada enerji korunumu denklemini kinetik enerji için yazamazsın. İşaret yönünü baştan seç.'],
 ['Elektrik · Ohm ve güç',3,'Ohmik direnç için V=IR, güç P=VI=I²R=V²/R. Seri dirençlerde akım, paralel dirençlerde gerilim aynıdır. Sonucu yazarken volt, amper, ohm ve watt birimlerini kontrol et.'],
 ['Ölçüm · Birim analizi',3,'Bir denklemin iki tarafının boyutları eşleşmeli. Hız m/s, ivme m/s², kuvvet kg·m/s². Sayısal işlemden önce birimleri kontrol etmek hatalı formülleri hızlıca yakalar.']
 ] as const
 const questions=[['Limitte 0/0 görünce ne yapmalıyım?',1,'x²−1 ifadesini (x−1)(x+1) olarak çarpanlarına ayır. Sadeleştirme yalnızca x≠1 için geçerlidir; limit alınırken noktanın yakınındaki davranış yeterlidir.'],['Türev sıfırsa kesin minimum mudur?',1,'Hayır. x³ fonksiyonunda x=0 için türev sıfırdır ama ekstremum yoktur. Türevin işaret değişimini veya uygun olduğunda ikinci türev testini incele.'],['Python listesine kopya almak için atama yeterli mi?',2,'b=a aynı listeye ikinci bir referans verir. Sığ kopya için a.copy() kullanabilirsin. İç içe değişebilir nesnelerde sığ kopyanın iç öğeleri paylaşacağını unutma.'],['Rekürsiyonda taban durum neden gerekli?',2,'Taban durum yeni çağrıları durdurur. Her çağrının problemi taban duruma yaklaştırdığını da kontrol et; yalnızca bir if eklemek sonlanmayı garanti etmez.'],['Sürtünme kuvveti her zaman μN mi?',3,'Kinetik sürtünme basit modelde μkN olur. Statik sürtünme ise gerektiği kadar büyür ve en fazla μsN değerine ulaşır.'],['Etki tepki kuvvetleri birbirini götürmez mi?',3,'Bu kuvvetler farklı cisimler üzerinde etkir. Tek bir cismin serbest cisim diyagramında birlikte bulunmazlar. İki cisimli sistemi birlikte ele aldığında iç kuvvet olarak birbirini götürürler.']] as const
 const goods=[['Ayarlanabilir masa lambası','Mobilya',320,'Üç ışık seviyesi, çalışma masasına uygun.'],['Dizüstü bilgisayar standı','Elektronik',250,'Katlanabilir alüminyum stand.'],['Teknik çizim seti','Ders malzemesi',420,'Pergel, cetvel ve çizim kalemleri.'],['Fizik problem kitabı','Kitap',190,'Mekanik ve elektrik alıştırmaları.'],['Ofis sandalyesi','Mobilya',1200,'Yüksekliği ayarlanabilir, yerinden teslim.'],['USB klavye ve fare','Elektronik',350,'Kablolu set, ders çalışmak için.'],['Diş hekimliği model seti','Ders malzemesi',650,'Preklinik derslerde kullanılan eğitim modeli; klinik kullanım için değildir.'],['Sırt çantası','Diğer',400,'Laptop bölmeli, günlük kampüs kullanımı.']] as const
 const clubs=[['Fotoğraf Topluluğu','Sanat','FT','pink','Kampüste ışık ve kompozisyon yürüyüşü'],['Sinema ve Kültür','Sanat','SK','lavender','Kısa film üzerine sohbet'],['Robotik Atölyesi','Teknoloji','RA','blue','Sensörlerle ilk proje'],['Gönüllülük Topluluğu','Sosyal','GT','green','Yeni dönem gönüllü tanışması'],['Münazara Topluluğu','Sosyal','MT','yellow','Argüman kurma atölyesi'],['Müzik Topluluğu','Sanat','MÜ','pink','Akustik tanışma buluşması']] as const
 for(let u=1;u<=3;u++){
  const base=u*1000,university_id=id(u),owned={user_id:id(901),created_at:at(-12),is_example:true},districts=u===1?['Maslak','Sarıyer','Kağıthane']:u===2?['Davutpaşa','Esenler','Güngören']:['Göztepe','Kadıköy','Kozyatağı']
  notes.forEach(([title,course,body],i)=>d.posts.push({...owned,id:id(base+100+i),university_id,course_id:id(base+course),kind:'note',title,body:body+'\n\nKampüsKit için hazırlanmış örnek çalışma notu; resmi ders materyali değildir.',link_url:null,attachment_path:null,published:true}))
  questions.forEach(([title,course,answer],i)=>{d.posts.push({...owned,id:id(base+120+i),university_id,course_id:id(base+course),kind:'question',title,body:'Bu konuyu tekrar ederken takıldım. Bir örnekle açıklayabilir misiniz?\n\nÖrnek öğrenci sorusu.',link_url:null,attachment_path:null,published:true});d.replies.push({id:id(base+140+i),user_id:id(902+i%3),created_at:at(-5),post_id:id(base+120+i),body:answer})})
  goods.forEach(([title,category,price,description],i)=>d.listings.push({...owned,id:id(base+160+i),university_id,kind:'market',title,category,price_kurus:price*100,description:description+' Örnek ilan; gerçek ürün satışı yapılmaz.',district:districts[i%3],deposit_kurus:0,available_from:null,lifestyle:'',contact:'',image_path:null,status:'active'}))
  for(let i=0;i<3;i++)for(const kind of ['housing','roommate'] as const)d.listings.push({...owned,id:id(base+180+i+(kind==='housing'?0:10)),university_id,kind,title:kind==='housing'?[ 'Toplu ulaşıma yakın 1+1','İki öğrenciye uygun 2+1','Eşyalı stüdyo devri'][i]:['Sessiz çalışma düzenine uygun arkadaş','Ortak alanlara özen gösteren ev arkadaşı','Yeni dönemde birlikte eve çıkalım'][i],category:kind==='housing'?['1+1','2+1','Stüdyo'][i]:'Oda arkadaşı',price_kurus:(kind==='housing'?17000+i*3000:7000+i*1500)*100,deposit_kurus:kind==='housing'?1700000:0,district:districts[i],available_from:at(24*(7+i)).slice(0,10),lifestyle:['Sigara içilmiyor · Sessiz çalışma','Evcil hayvana uygun · Düzenli temizlik','Ortak bütçe planı · Erken uyku'][i],description:'Bu ilan, barınma filtrelerini ve öğrenci ihtiyaçlarını göstermek için oluşturuldu. Gerçek bir kiralık mülk veya kişi ilanı değildir.',contact:'',image_path:null,status:'active'})
  clubs.forEach(([name,category,initials,color,event],i)=>{const club_id=id(base+210+i);d.clubs.push({id:club_id,university_id,name,category,initials,color,description:'İlgi alanını paylaşan öğrenciler için atölyeler ve buluşmalar. Demo topluluğudur; resmi üniversite kulübü değildir.',is_example:true});for(let j=0;j<2;j++)d.club_events.push({id:id(base+230+i*2+j),club_id,title:j?name+' · Proje buluşması':event,starts_at:at(48+i*24+j*168),location:'Öğrenci merkezi · Örnek salon',description:'Takvim akışını denemek için örnek etkinlik. Gerçek bir etkinlik veya rezervasyon değildir.',is_example:true})})
  ;['Ders Arası Sandviç','Prizli Masa','Çorba Molası'].forEach((name,i)=>{const place_id=id(base+260+i);d.places.push({id:place_id,university_id,campus_id:id(base),name,category:i===1?'Çalışma':'Yemek',price_level:1,district:districts[i],description:'Öğrenci öneri ekranı için hazırlanmış temsili mekan; gerçek bir işletme veya fiyat teklifi değildir.',symbol:i===1?'book':'utensils',is_example:true});d.reviews.push({id:id(base+270+i),user_id:id(902),place_id,created_at:at(-8),rating:4,body:'Örnek deneyim: ders arasında hızlı bir mola için uygun.'})})
 }
 const nowDate=new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Istanbul'})
 const expenses=[['Ders','Defter ve kalem',18000],['Yemek','Kampüs öğle yemeği',9500],['Sosyal','Sinema',18000],['Diğer','Telefon faturası',24000],['Yemek','Market alışverişi',52000]] as const
 expenses.forEach(([category,note,amount_kurus],i)=>d.budget_entries.push({id:id(7300+i),user_id:id(900),created_at:at(-20+i),type:'expense',amount_kurus,category,note,occurred_on:nowDate}))
 d.budget_entries.push({id:id(7310),user_id:id(900),created_at:at(-30),type:'income',amount_kurus:300000,category:'Burs',note:'Örnek burs ödemesi',occurred_on:nowDate})
 ;['Fizik I · Problem seti','Takım projesi sunumu','Kulüp atölyesi','Lineer cebir tekrarı'].forEach((title,i)=>d.calendar_items.push({id:id(7400+i),user_id:id(900),created_at:at(-4),title,kind:i===2?'event':i===3?'exam':'deadline',due_at:at(72+i*24),reminder_minutes:60,email_enabled:false,completed:false,club_event_id:null,revision:1}))
}
