import {enrichExamples} from './seed-extra.ts'
import {emptyData} from './types.ts'
import type {DatabaseState,Profile} from './types.ts'
import {dateKey} from './domain.ts'
export const uuid=(n:number)=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0')
export const demoUser=uuid(900)
export const demoProfile:Profile={id:demoUser,display_name:'Deniz',university_id:uuid(1),department:'Bilgisayar Mühendisliği'}
export function createExampleData():DatabaseState{
const d=emptyData(),now=new Date(),at=(hours:number)=>new Date(now.getTime()+hours*3600000).toISOString(),owned={user_id:uuid(901),created_at:at(-24),is_example:true}
d.universities=[{id:uuid(1),name:'İstanbul Teknik Üniversitesi',short_name:'İTÜ',city:'İstanbul'},{id:uuid(2),name:'Yıldız Teknik Üniversitesi',short_name:'YTÜ',city:'İstanbul'},{id:uuid(3),name:'Marmara Üniversitesi',short_name:'Marmara',city:'İstanbul'}]
d.members=[{id:demoUser,display_name:'Deniz'},{id:uuid(901),display_name:'Ece D.'},{id:uuid(902),display_name:'Arda K.'},{id:uuid(903),display_name:'Zeynep M.'},{id:uuid(904),display_name:'Mert · Örnek'},{id:uuid(905),display_name:'Elif · Örnek'}]
for(let u=1;u<=3;u++){const university_id=uuid(u),base=u*1000;
d.campuses.push({id:uuid(base),university_id,name:u===1?'Ayazağa':u===2?'Davutpaşa':'Göztepe',latitude:[41.101422,41.025694,40.986114][u-1],longitude:[29.021206,28.888035,29.05335][u-1],source_url:['https://sustecs.itu.edu.tr/bize-ulasin/','https://erasmus.yildiz.edu.tr/page/Erasmus--Europe/Campuses/852','https://sks.marmara.edu.tr/contact'][u-1]})
d.courses.push({id:uuid(base+1),university_id,name:'Matematik I',code:'MAT 101'},{id:uuid(base+2),university_id,name:'Programlamaya Giriş',code:'BLG 101'},{id:uuid(base+3),university_id,name:'Fizik I',code:'FIZ 101'})
d.internships.push(...[{title:'Frontend Geliştirici Stajyeri',company:'Piksel Teknoloji',field:'Yazılım',work_mode:'Hibrit',description:'React ve TypeScript ile ürün geliştiren bir ekiple tanış. Üniversite öğrencilerine yönelik örnek yaz stajı ilanı.'},{title:'Ürün Tasarımı Stajyeri',company:'Forma Studio',field:'Tasarım',work_mode:'Uzaktan',description:'Araştırmadan prototipe, dijital ürün tasarımının bütün aşamalarını keşfet.'},{title:'Pazarlama Stajyeri',company:'Yeni Nesil',field:'İşletme',work_mode:'Ofiste',description:'İçerik, iletişim ve sosyal medya alanlarında deneyim kazan.'}].map((r,i)=>({...r,id:uuid(base+10+i),university_id,location:'İstanbul',is_example:true,source_url:null,deadline:at(240+i*48)})))
d.posts.push({id:uuid(base+20),...owned,university_id,course_id:uuid(base+1),kind:'note',title:'Limit ve süreklilik · Vizeye hazırlık',body:'Limit kuralları, sağdan ve soldan limit, süreklilik koşulları.\n\n1. Fonksiyonun noktadaki değeri tanımlı olmalı.\n2. Sağ ve sol limitler eşit olmalı.\n3. Limit, fonksiyonun değerine eşit olmalı.\n\nBu paylaşım, not ekranını göstermek için hazırlanmış örnek içeriktir.',link_url:null,attachment_path:null,published:true},{id:uuid(base+21),...owned,user_id:uuid(902),university_id,course_id:uuid(base+2),kind:'question',title:'Döngülerin zaman karmaşıklığını nasıl hesaplıyoruz?',body:'İç içe döngülerde hangi durumda O(n²) oluyor? Küçük bir örnekle açıklayabilir misiniz?',link_url:null,attachment_path:null,published:true},{id:uuid(base+22),...owned,user_id:uuid(903),university_id,course_id:uuid(base+3),kind:'note',title:'Newton yasaları · Kısa tekrar notları',body:'Kuvvet, kütle ve ivme ilişkisi: F = m × a.\nSerbest cisim diyagramı çizerken her kuvveti ayrı göster.\nEtki ve tepki kuvvetlerinin farklı cisimlere uygulandığını unutma.',link_url:null,attachment_path:null,published:true})
d.replies.push({id:uuid(base+25),user_id:uuid(903),created_at:at(-3),post_id:uuid(base+21),body:'İki döngü de birbirinden bağımsız olarak n kez çalışıyorsa toplam n × n işlem olur. İç döngü sabit sayıda çalışıyorsa sonuç O(n) kalır.'})
d.listings.push(...[{kind:'market' as const,title:'Casio bilimsel hesap makinesi',description:'Derslerde kullanıldı, bütün tuşları çalışıyor. Kutusu ve kılıfı mevcut.',category:'Ders malzemesi',price_kurus:45000,district:u===1?'Maslak':'Kadıköy'},{kind:'market' as const,title:'Calculus · Temiz kullanılmış',description:'Matematik I ve II için kaynak. Sayfalarda az miktarda kurşun kalem notu var.',category:'Kitap',price_kurus:28000,district:'Kampüs'},{kind:'market' as const,title:'Ahşap çalışma masası',description:'Yeni eve taşınırken devrediyorum. 120 × 60 cm, yerinden teslim.',category:'Mobilya',price_kurus:90000,district:'Beşiktaş'},{kind:'housing' as const,title:'Kampüse yakın, aydınlık 2+1',description:'Metroya yürüme mesafesinde, eşyalı öğrenci evi. Evi dönem sonunda devretmek istiyoruz.',category:'2+1',price_kurus:2200000,district:'Kağıthane'},{kind:'housing' as const,title:'Metro yanı eşyalı 1+1',description:'Sessiz sokakta, toplu ulaşıma yakın. Buzdolabı ve çamaşır makinesi dahil.',category:'1+1',price_kurus:1750000,district:'Şişli'},{kind:'roommate' as const,title:'Birlikte güzel bir ev kuralım',description:'İkinci sınıf öğrencisiyim. Ortak alanlara özen gösteren bir ev arkadaşı arıyorum.',category:'Oda arkadaşı',price_kurus:1000000,district:'Sarıyer'},{kind:'roommate' as const,title:'Evimizde bir oda boşalıyor',description:'Üç kişilik evimizde aydınlık bir oda. Evde çoğunlukla ders çalışıyoruz.',category:'Oda arkadaşı',price_kurus:850000,district:'Kadıköy'}].map((r,i)=>({...r,...owned,id:uuid(base+30+i),university_id,deposit_kurus:r.kind==='housing'?r.price_kurus:0,available_from:dateKey(new Date(at(168))),lifestyle:'Sigara içilmiyor · Ortak alanlarda düzen',contact:'',image_path:null,status:'active' as const})))
d.places.push(...[{name:'Mola Kahve',category:'Kafe',price_level:2,district:'Kampüs çevresi',description:'Ders aralarında kahve, geniş masalar ve priz. Öğrenci menüsü bulunan örnek mekan.',symbol:'coffee'},{name:'Kampüs Sofrası',category:'Yemek',price_level:1,district:'Merkez',description:'Günün yemeği, çorba ve ev yemekleri. Uygun fiyatlı öğle arası için.',symbol:'utensils'},{name:'Kitap Arası',category:'Çalışma',price_level:2,district:'Kampüs çevresi',description:'Sessiz çalışma alanı, kütüphane rafları ve filtre kahve.',symbol:'book'}].map((r,i)=>({...r,id:uuid(base+40+i),university_id,is_example:true})))
d.reviews.push(...[5,4,5].map((rating,i)=>({id:uuid(base+45+i),user_id:uuid(901+i),created_at:at(-12),place_id:uuid(base+40),rating,body:['Çalışmak için güzel masalar var.','Kahvesi iyi, öğleden sonra biraz kalabalık.','Öğrenci menüsünü sevdim.'][i]})))
d.clubs.push(...[{name:'Girişimcilik Kulübü',category:'Kariyer',description:'Fikrini büyüt, yeni insanlarla tanış. Atölyeler ve kurucu buluşmaları.',initials:'GK',color:'yellow'},{name:'Yazılım ve Teknoloji',category:'Teknoloji',description:'Birlikte kod yazıyoruz. Açık kaynak, hackathon ve teknoloji sohbetleri.',initials:'YT',color:'blue'},{name:'Doğa ve Gezi Kulübü',category:'Sosyal',description:'Şehrin dışına bir adım. Hafta sonu yürüyüşleri ve yeni rotalar.',initials:'DG',color:'green'}].map((r,i)=>({...r,id:uuid(base+50+i),university_id,is_example:true})))
d.club_events.push({id:uuid(base+60),club_id:uuid(base+50),title:'Bir fikirden ilk ürüne',starts_at:at(28),location:'Merkez amfi',description:'Fikirlerini somut bir ürüne dönüştürmek için bir giriş atölyesi.',is_example:true},{id:uuid(base+61),club_id:uuid(base+51),title:'Tanışalım, birlikte üretelim',starts_at:at(54),location:'Öğrenci merkezi',description:'Yeni dönem tanışması ve proje ekipleri buluşması.',is_example:true})
d.crowd_locations.push({id:uuid(base+70),university_id,campus_id:uuid(base),name:'Merkez Kütüphane',kind:'library'},{id:uuid(base+71),university_id,campus_id:uuid(base),name:'Ana Yemekhane',kind:'dining'})
d.crowd_reports.push(...[1,1,2,2,3].map((level,i)=>({id:uuid(base+80+i),user_id:uuid(901+i),created_at:at(-.12-i*.07),is_example:true,location_id:uuid(base+(i<3?70:71)),level:level as 1|2|3})))
}
d.budget_entries=[{id:uuid(7001),user_id:demoUser,created_at:at(-40),type:'income',amount_kurus:1200000,category:'Aylık destek',note:'Eylül bütçesi',occurred_on:dateKey(now)},{id:uuid(7002),user_id:demoUser,created_at:at(-8),type:'expense',amount_kurus:325000,category:'Barınma',note:'Kira payı',occurred_on:dateKey(now)},{id:uuid(7003),user_id:demoUser,created_at:at(-7),type:'expense',amount_kurus:148000,category:'Yemek',note:'Haftalık yemek',occurred_on:dateKey(now)},{id:uuid(7004),user_id:demoUser,created_at:at(-6),type:'expense',amount_kurus:57000,category:'Ulaşım',note:'İstanbulkart',occurred_on:dateKey(now)}]
d.calendar_items=[{id:uuid(7101),user_id:demoUser,created_at:at(-5),title:'Matematik I · Kısa sınav',kind:'exam',due_at:at(23),reminder_minutes:1440,email_enabled:false,completed:false,club_event_id:null,revision:1},{id:uuid(7102),user_id:demoUser,created_at:at(-5),title:'Programlama ödevi teslimi',kind:'deadline',due_at:at(51),reminder_minutes:1440,email_enabled:false,completed:false,club_event_id:null,revision:1}]
d.club_follows=[{id:uuid(7201),user_id:demoUser,club_id:uuid(1050)}]
enrichExamples(d,uuid,at)
return d
}
